Add Contact form
Lasten-Ernest/Lasten-Ernest-Portfolio-Website pull request #2
Opened 2022-06-01 11:21 UTC by Lasten-Ernest

This pull request is for adding a contact form in the portfolio project. The contact form section is a collaboration work between me, Ernest and my partner, Dorian.

2022-06-01 21:14 UTC, ShahierNashaat requested changes
Hi @Lasten-Ernest and @dodoburner , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-01 21:14 UTC, ShahierNashaat commented on index.html
> +				<input name="name" type="text" placeholder="Name">
- [ ] Kindly be noticed that the name should have maxlength="30" and required attributes.

2022-06-01 21:14 UTC, ShahierNashaat commented on index.html
> +				<textarea name="message" id="message" placeholder="Write your message here"></textarea>
- [ ] Kindly be noticed that the message should have maxlength="500" and required attributes.

2022-06-01 21:14 UTC, ShahierNashaat commented on index.html
> +				<input name="email" type="email" placeholder="Email">
- [ ] Kindly be noticed that the email should have a required attribute.

2022-06-02 07:21 UTC, sja-thedude approved these changes
## Project Approved 👍 

Hi @Lasten-Ernest, This is @sja-thedude your code reviewer.

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![giphy](https://user-images.githubusercontent.com/70269507/159485323-11dfc0c5-bd53-4956-b55a-2fc42f7a3845.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-02 07:28 UTC, merged